import { useState } from "react";
import { formatRecord, onlineRanking, type RankEntry } from "./rankings";
export default function Leaderboard({entries, rps, ko, error=false}:{entries:RankEntry[];rps:boolean;ko:boolean;error?:boolean}) {
  return <section className="leaderboard"><header><b>TOP 10</b><span>{onlineRanking?(ko?"온라인 순위":"ONLINE RANKING"):(ko?"로컬 테스트 순위":"LOCAL TEST RANKING")}</span></header><p>{ko?"1위의 진영이 포탈 점령 · 동점은 먼저 등록한 기록 우선":"#1 CONTROLS THE PORTAL · EARLIER RECORD WINS TIES"}</p>{error?<p role="alert">{ko?"순위를 불러오지 못했습니다. 잠시 후 다시 시도합니다.":"Rankings unavailable. Retrying shortly."}</p>:<ol>{Array.from({length:10},(_,i)=>{const r=entries[i];return <li key={i}><span>{String(i+1).padStart(2,"0")}</span><div><b>{r?.nickname??"—"}</b>{r&&<small>{r.team.toUpperCase()}</small>}</div><strong>{r?formatRecord(r.value,rps):"—"}</strong></li>;})}</ol>}</section>;
}
export function RecordEntry({value,rps,ko,onSave,onClose}:{value:number;rps:boolean;ko:boolean;onSave:(name:string)=>Promise<void>;onClose:()=>void}){
  const [name,setName]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  return <div className="record-scrim"><section className="record-dialog" role="dialog" aria-modal="true" aria-labelledby="record-title"><span>RUN COMPLETE</span><h2 id="record-title">{formatRecord(value,rps)}</h2><p>{ko?"닉네임으로 최고 기록을 등록하세요. 상위 10위에 표시되며 1위가 포탈을 점령합니다.":"Register your personal best. The top 10 appear here; #1 controls the portal."}</p><small>{onlineRanking?"ONLINE RANKING":(ko?"온라인 미연결 · 이 브라우저의 테스트 기록만 저장됩니다.":"OFFLINE SETUP · Test records stay in this browser.")}</small><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await onSave(name);}catch{setError(ko?"저장에 실패했습니다. 연결 상태를 확인하고 다시 시도하세요.":"Could not save. Check your connection and retry.");setBusy(false);}}}><label>{ko?"닉네임":"NICKNAME"}<input autoFocus maxLength={20} required value={name} onChange={e=>setName(e.target.value)} disabled={busy}/></label>{error&&<p role="alert">{error}</p>}<button className="pixel-button" disabled={busy||!name.trim()}>{busy?"SAVING…":(ko?"기록 등록":"SUBMIT RECORD")}</button><button type="button" className="cabinet-exit" disabled={busy} onClick={onClose}>{ko?"등록하지 않고 나가기":"SKIP RECORD"}</button></form></section></div>;
}
